version: '3.8'
name: micro-express
services:
    postgres:
        image: postgres:10.4
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: micro-express
volumes:
    node_modules:
